#!/usr/bin/env bash
set -euo pipefail

# AI Workflow — Codex Adapter Uninstaller
# Removes ~/.codex/AGENTS.md (and legacy instructions.md) if generated by aiwf.

CODEX_DIR="${CODEX_DIR:-$HOME/.codex}"
OUT_FILE="$CODEX_DIR/AGENTS.md"
LEGACY_FILE="$CODEX_DIR/instructions.md"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

echo ""
echo "=== AI Workflow — Codex Uninstaller ==="
echo ""

removed=0
for f in "$OUT_FILE" "$LEGACY_FILE"; do
    [ -f "$f" ] || continue
    if grep -q "aiwf — AI Workflow compiled instructions" "$f" 2>/dev/null; then
        rm "$f"
        info "Removed $f"
        removed=1
    else
        warn "$f exists but was not generated by aiwf — leaving it untouched"
    fi
done

if [ $removed -eq 0 ]; then
    warn "Nothing to remove in $CODEX_DIR"
fi

echo ""
