#!/usr/bin/env bash
set -euo pipefail

# AI Workflow — Codex Adapter Uninstaller
# Removes ~/.codex/instructions.md if it was generated by aiwf.

CODEX_DIR="${CODEX_DIR:-$HOME/.codex}"
OUT_FILE="$CODEX_DIR/instructions.md"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

echo ""
echo "=== AI Workflow — Codex Uninstaller ==="
echo ""

if [ ! -f "$OUT_FILE" ]; then
    warn "$OUT_FILE not found — nothing to remove"
    exit 0
fi

# Only remove if it was generated by aiwf (check the header comment).
if grep -q "aiwf — AI Workflow compiled instructions" "$OUT_FILE" 2>/dev/null; then
    rm "$OUT_FILE"
    info "Removed $OUT_FILE"
else
    warn "$OUT_FILE exists but was not generated by aiwf — leaving it untouched"
fi

echo ""
