#!/usr/bin/env bash
set -euo pipefail

# AI Workflow — Codex Adapter Uninstaller
#
# Removes aiwf-installed bits for Codex CLI:
#   - ~/.agents/skills/aiwf-* symlinks
#   - ~/.codex/AGENTS.md (if generated by aiwf)
#   - ~/.codex/instructions.md (legacy, if generated by aiwf)

CODEX_DIR="${CODEX_DIR:-$HOME/.codex}"
AGENTS_DIR="${AGENTS_DIR:-$HOME/.agents}"
SKILLS_DIR="$AGENTS_DIR/skills"
OUT_FILE="$CODEX_DIR/AGENTS.md"
LEGACY_FILE="$CODEX_DIR/instructions.md"
SKILL_PREFIX="aiwf-"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

echo ""
echo "=== AI Workflow — Codex Uninstaller ==="
echo ""

removed=0

# Remove aiwf-* skill symlinks.
if [ -d "$SKILLS_DIR" ] && compgen -G "$SKILLS_DIR/${SKILL_PREFIX}*" > /dev/null; then
    for link in "$SKILLS_DIR/${SKILL_PREFIX}"*; do
        if [ -L "$link" ]; then
            rm "$link"
            info "Removed $link"
            removed=1
        fi
    done
fi

# Remove AGENTS.md + legacy instructions.md (only if we generated them).
for f in "$OUT_FILE" "$LEGACY_FILE"; do
    [ -f "$f" ] || continue
    if grep -q "aiwf — AI Workflow compiled instructions" "$f" 2>/dev/null; then
        rm "$f"
        info "Removed $f"
        removed=1
    else
        warn "$f exists but was not generated by aiwf — leaving it untouched"
    fi
done

if [ $removed -eq 0 ]; then
    warn "Nothing to remove"
fi

echo ""
